project_id = "uwguclfaeplxehwifurl"

[functions.send-invite-email]
verify_jwt = true

[functions.send-reset-email]
verify_jwt = false

[functions.password-reset-request]
verify_jwt = false

[functions.password-reset-confirm]
verify_jwt = false
